model_dir: model/best
scores_dir: scores
datasets_dir: /data2/Run3_HLT/prod_v3-eval
algo_params_dir: algos
variables_dir: vars
performance_dir: perf
scores_diff_dir: hls4ml/scores_diff
model_stat_file: model_stat.json
model_summary_file: model_summary.txt
eval_hls4ml: true
apply_training:
  batch_size: 5000
  regress_pt: false
hls4ml:
  output_dir: hls4ml
  fpga_part: xc7vx690t-ffg1927-2
  config_customizations:
    Model:
      Precision: fixed<22,9>
    LayerName:
      dense1:
        Precision:
          result: fixed<22,9>
      dense1_linear:
        Precision:
          result: fixed<22,9>
      dense2:
        Precision:
          result: fixed<22,9>
      dense2_linear:
        Precision:
          result: fixed<22,9>
      dense3:
        Precision:
          result: fixed<22,9>
      dense3_linear:
        Precision:
          result: fixed<22,9>
      input_all:
        Precision:
          result: int<10>
datasets:
  HTT:
    file: GluGluHToTauTau_M-125.root
    title: "$H\\to\\tau\\tau$"
  HH:
    file: GluGlutoHHto2B2Tau_kl-1p00_kt-1p00_c2-0p00.root
    title: "$HH\\to bb\\tau\\tau$"
  HTT_1tau:
    file: GluGluHToTauTau_M-125_1tau.root
    title: "$H\\to\\tau\\tau$ 1 $\\tau_h$"
  HH_1tau:
    file: GluGlutoHHto2B2Tau_kl-1p00_kt-1p00_c2-0p00_1tau.root
    title: "$HH\\to bb\\tau\\tau$ 1 $\\tau_h$"
  ZeroBias_2022G:
    file: ZeroBias_Run2022G_362696.root
    title: "ZeroBias Run2022G run=362696"
variables:
  rate:
    datasets: [ ZeroBias_2022G ]
    scope: dataset
    value_type: rate
  efficiency:
    datasets: [ HTT, HH, HH_1tau ]
    scope: dataset
    value_type: efficiency
  L1Tau_gen_pt:
    scope: tau
    datasets: [ HTT, HH, HH_1tau ]
    bins: [ 20, 25, 30, 35, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160, 180, 200, 250, 300, 350, 400, 450, 500, 600, 800, 1000 ]
    major_ticks: [ 20, 30, 40, 50, 70, 100, 200, 300, 500, 1000 ]
    minor_ticks: [ 60, 80, 90, 400, 600, 700, 800, 900 ]
    xlabel: "gen visible $p_{T}$ (GeV)"
    xscale: log
    yscale: log
  L1Tau_gen_pt_midPt:
    column: L1Tau_gen_pt
    scope: tau
    datasets: [ HTT, HH, HH_1tau ]
    bins: [ 40, 50, 60, 80, 100, 150, 200, 300 ]
    major_ticks: [ 40, 50, 100, 150, 200, 300 ]
    minor_ticks: [ 60, 70, 80, 90, 250 ]
    xlabel: "gen visible $p_{T}$ (GeV)"
    xscale: log
  L1Tau_gen_pt_highPt:
    column: L1Tau_gen_pt
    scope: tau
    datasets: [ HTT, HH, HH_1tau ]
    bins: [ 70, 80, 90, 100, 120, 140, 160, 180, 200, 300, 500, 1000 ]
    major_ticks: [ 70, 100, 140, 200, 300, 500, 1000 ]
    minor_ticks: [ 80, 90 ]
    xlabel: "gen visible $p_{T}$ (GeV)"
    xscale: log
  L1Tau_gen_eta:
    scope: tau
    datasets: [ HTT, HH, HH_1tau ]
    bins: [ -2.5, -2.1, -1.7, -1, -0.5, 0, 0.5, 1, 1.7, 2.1, 2.5 ]
    xlabel: "gen visible $\\tau_h$ $\\eta$ (GeV)"
  L1Tau_pt:
    scope: tau
    datasets: [ HTT, HH, HH_1tau ]
    bins: [ 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 45, 50, 60, 70, 80, 90, 100, 120, 150, 200, 255, 300 ]
    major_ticks: [ 30, 40, 50, 70, 100, 150, 200, 255 ]
    minor_ticks: [ 60, 80, 90, 110, 120, 130, 140, 160, 170, 180, 190, 210, 220, 230, 240, 250 ]
    xlabel: "L1Tau $p_{T}$ (GeV)"
    xscale: log
    ylim: [0.0, 1.005]
  L1Tau_eta:
    scope: tau
    datasets: [ HTT, HH, HH_1tau ]
    bins: [ -2.5, -2.1, -1.7, -1, -0.5, 0, 0.5, 1, 1.7, 2.1, 2.5 ]
    xlabel: "L1Tau $\\eta$ (GeV)"
  L1Tau_Jet_pt:
    scope: tau
    datasets: [ HTT, HH, HH_1tau ]
    bins: [ 30, 32, 34, 36, 38, 40, 45, 50, 60, 70, 80, 90, 100, 120, 140, 160, 180, 200, 300, 500, 1000 ]
    major_ticks: [ 30, 40, 50, 70, 100, 140, 200, 300, 500, 1000 ]
    minor_ticks: [ 60, 80, 90 ]
    xlabel: "HLT PF Jet $p_{T}$ (GeV)"
    xscale: log
  L1Tau_Jet_pt_midPt:
    column: L1Tau_Jet_pt
    scope: tau
    datasets: [ HTT, HH, HH_1tau ]
    bins: [ 40, 50, 60, 80, 100, 150, 200, 300 ]
    major_ticks: [ 40, 50, 100, 150, 200, 300 ]
    minor_ticks: [ 60, 70, 80, 90, 250 ]
    xlabel: "HLT PF Jet $p_{T}$ (GeV)"
    xscale: log
  L1Tau_Jet_pt_highPt:
    column: L1Tau_Jet_pt
    scope: tau
    datasets: [ HH, HH_1tau ]
    bins: [ 70, 80, 90, 100, 120, 140, 160, 180, 200, 300, 500, 1000 ]
    major_ticks: [ 70, 100, 140, 200, 300, 500, 1000 ]
    minor_ticks: [ 80, 90 ]
    xlabel: "HLT PF Jet $p_{T}$ (GeV)"
    xscale: log
  GenHH_mass:
    scope: event
    datasets: [ HH ]
    bins: [ 250, 300, 350, 400, 450, 500, 550, 600, 700, 800, 900, 1000 ]
    xlabel: "gen $m_{HH}$ (GeV)"
    #xlim: [250, 2000]
    #ylim: [ -1, 1]
  GenHtt_pt:
    scope: event
    datasets: [ HTT, HH ]
    bins: [ 0, 50, 100, 150, 200, 250, 300, 350, 400, 500, 700, 1000 ]
    xlabel: "gen $H\\to\\tau\\tau$ $p_T$ (GeV)"
plots:
  efficiency:
    datasets: [ HH, HTT ]
    variables: all
    variants:
      ditau_v1:
        # - algo: reco_2tau_25
        #   title: "$p_T\\geq 25$ GeV @120.3kHz"
        #   color: "#808080"
        - algo: reco_2tau_34
          title: "$p_T\\geq 34$ GeV @20.3kHz"
          color: "#929591"
        - algo: default_2tau
          title: "$p_T\\geq 34$ GeV && L1 iso @9.8kHz"
          color: k
        - algo: default_2tau_36
          title: "$p_T\\geq 36$ GeV && L1 iso @8.3kHz"
          color: "#808080"
        - algo: nn_2tau_eff
          title: "$p_T\\geq 25$ GeV && ShallowTau eff tune @9.8kHz"
          color: y
        - algo: nn_2tau_rate
          title: "$p_T\\geq 25$ GeV && ShallowTau rate tune v1 @8.2kHz"
          color: b
        # - algo: nn_2tau_rate_95_98
        #   title: "$p_T\\geq 25$ GeV && ShallowTau rate tune v2 @7.5kHz"
        #   color: g
        # - algo: nn_2tau_rate_90_95
        #   title: "$p_T\\geq 25$ GeV && ShallowTau rate tune v3 @6.5kHz"
        #   color: r
      ditau_HT_v1:
        - algo: default_2tau_HT
          title: "L1_DoubleIsoTau34er2p1"
          color: k
        - algo: nn_2tau_eff_HT
          title: "ShallowTau (eff tune)"
          color: y
        - algo: nn_2tau_rate_HT
          title: "ShallowTau (rate tune)"
          color: b
  efficiency_1tau:
    datasets: [ HH_1tau ]
    variables: all
    variants:
      tau_v1:
        - algo: default_1tau
          title: "$p_T\\geq 120$ GeV @1.78kHz"
          color: k
        - algo: nn_1tau
          title: "$p_T\\geq 70$ GeV && ShallowTau eff tune @1.78kHz"
          color: y
        - algo: nn_1tau_rate
          title: "$p_T\\geq 70$ GeV && ShallowTau rate tune @1.61kHz"
          color: b
lut_bins:
  nn_1tau: [ 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250 ]
  nn_2tau: [ 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 42, 44, 46, 48, 50, 55, 60, 65, 70, 80, 90, 100, 120, 150, 200, 255 ]
algorithms:
  reco_2tau_25:
    algo: default
    n_taus: 2
    pt_noiso_thr: 25
  reco_2tau_34:
    algo: default
    n_taus: 2
    pt_noiso_thr: 34
  default_2tau:
    algo: default
    n_taus: 2
    pt_iso_thr: 34
    pt_noiso_thr: 70
  default_2tau_36:
    algo: default
    n_taus: 2
    pt_iso_thr: 36
    pt_noiso_thr: 70
  default_1tau:
    algo: default
    n_taus: 1
    pt_noiso_thr: 120
  L1_HT:
    algo: l1_flag
    l1_flag: L1_HTT280er
    valid_per_tau: false
  nn_2tau_eff:
    algo: nn
    n_taus: 2
    nn_var: L1Tau_NNtag_q
    lut_var: L1Tau_pt
    lut_bins: nn_2tau
    thresholds_opt:
      dataset_eff: HTT
      dataset_rate: ZeroBias_2022G
      target_rate: default_2tau
      tau_eff_dataset: HH
      tau_eff_var: L1Tau_gen_pt_highPt
      tau_eff_algo: default_2tau
      tau_eff_scale: 1
      step: 0.00390625
      extra_algos_eff: [ L1_HT ]
      target: Efficiency
  nn_2tau_rate:
    algo: nn
    n_taus: 2
    nn_var: L1Tau_NNtag_q
    lut_var: L1Tau_pt
    lut_bins: nn_2tau
    thresholds_opt:
      dataset_eff: HTT
      dataset_rate: ZeroBias_2022G
      target_rate: 100000.0 #default_2tau
      tau_eff_dataset: HH
      tau_eff_var: L1Tau_gen_pt_midPt
      tau_eff_algo: default_2tau
      tau_eff_scale: 1
      step: 0.00390625
      target: Rate
  nn_2tau_rate_90_95:
    algo: nn
    n_taus: 2
    nn_var: L1Tau_NNtag_q
    lut_var: L1Tau_pt
    lut_bins: nn_2tau
    thresholds_opt:
      dataset_eff: HTT
      dataset_rate: ZeroBias_2022G
      target_rate: 100000.0 #default_2tau
      tau_eff_dataset: HH
      tau_eff_var: L1Tau_gen_pt_midPt
      tau_eff_algo: default_2tau
      tau_eff_scale: [ 0.90, 0.95, 1, 1, 1, 1, 1 ]
      step: 0.00390625
      target: Rate
      initial_thresholds: nn_2tau_rate
  nn_2tau_rate_95_98:
    algo: nn
    n_taus: 2
    nn_var: L1Tau_NNtag_q
    lut_var: L1Tau_pt
    lut_bins: nn_2tau
    thresholds_opt:
      dataset_eff: HTT
      dataset_rate: ZeroBias_2022G
      target_rate: 100000.0 #default_2tau
      tau_eff_dataset: HH
      tau_eff_var: L1Tau_gen_pt_midPt
      tau_eff_algo: default_2tau
      tau_eff_scale: [ 0.95, 0.98, 1, 1, 1, 1, 1 ]
      step: 0.00390625
      target: Rate
      initial_thresholds: nn_2tau_rate
  nn_1tau:
    algo: nn
    n_taus: 1
    nn_var: L1Tau_NNtag_q
    lut_var: L1Tau_pt
    lut_bins: nn_1tau
    thresholds_opt:
      dataset_eff: HH_1tau
      dataset_rate: ZeroBias_2022G
      target_rate: default_1tau
      tau_eff_dataset: HH_1tau
      tau_eff_var: L1Tau_gen_pt_highPt
      tau_eff_algo: default_1tau
      tau_eff_scale: 1
      step: 0.00390625
  nn_1tau_rate:
    algo: nn
    n_taus: 1
    nn_var: L1Tau_NNtag_q
    lut_var: L1Tau_pt
    lut_bins: nn_1tau
    thresholds_opt:
      dataset_eff: HH_1tau
      dataset_rate: ZeroBias_2022G
      target_rate: 100000.0 #default_1tau
      tau_eff_dataset: HH_1tau
      tau_eff_var: L1Tau_gen_pt_highPt
      tau_eff_algo: default_1tau
      tau_eff_scale: 1
      step: 0.00390625
      target: Rate
      initial_thresholds: nn_1tau
  default_2tau_HT:
    algo: composite
    sub_algos:
      - default_2tau
      - L1_HT
  nn_2tau_eff_HT:
    algo: composite
    sub_algos:
      - nn_2tau_eff
      - L1_HT
  nn_2tau_rate_HT:
    algo: composite
    sub_algos:
      - nn_2tau_rate
      - L1_HT