model_dir: model/best
scores_dir: scores
datasets_dir: /data2/Run3_HLT/prod_v3-eval
algo_params_dir: algos
event_metrics_dir: event_metrics
differential_efficiency_dir: diff_eff
performance_dir: perf
apply_training:
  batch_size: 5000
datasets:
  HTT:
    file: GluGluHToTauTau_M-125.root
    title: "$H\to\tau\tau$"
  HH:
    file: GluGlutoHHto2B2Tau_kl-1p00_kt-1p00_c2-0p00.root
    title: "$HH\to bb\tau\tau$"
  ZeroBias_2022G:
    file: ZeroBias_Run2022G_362696.root
    title: "ZeroBias Run2022G run=362696"
event_metrics:
  rate:
    dataset: ZeroBias_2022G
    type: rate
  eff_HH:
    dataset: HH
    type: efficiency
  eff_HTT:
    dataset: HTT
    type: efficiency
variables:
  L1Tau_gen_pt:
    tau_var: true
    datasets: [ HTT, HH ]
    bins: [ 20, 25, 30, 35, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160, 180, 200, 250, 300, 350, 400, 450, 500, 600, 800, 1000 ]
    major_ticks: [ 20, 30, 40, 50, 70, 100, 200, 300, 500, 1000 ]
    minor_ticks: [ 60, 80, 90, 400, 600, 700, 800, 900 ]
    xlabel: "gen visible $p_{T}$ (GeV)"
    xscale: log
  L1Tau_gen_eta:
    tau_var: true
    datasets: [ HTT, HH ]
    bins: [ -2.5, -2.1, -1.7, -1, -0.5, 0, 0.5, 1, 1.7, 2.1, 2.5 ]
    xlabel: "gen visible $\\tau_h$ $\\eta$ (GeV)"
  L1Tau_pt:
    tau_var: true
    datasets: [ HTT, HH ]
    bins: [ 30, 32, 34, 36, 38, 40, 45, 50, 60, 70, 80, 90, 100, 120, 150, 200, 255, 300 ]
    major_ticks: [ 20, 30, 40, 50, 70, 100, 150, 200, 255 ]
    minor_ticks: [ 60, 80, 90, 110, 120, 130, 140, 160, 170, 180, 190 ]
    xlabel: "L1Tau $p_{T}$ (GeV)"
    xscale: log
    ylim: [0.0, 1.005]
  L1Tau_eta:
    tau_var: true
    datasets: [ HTT, HH ]
    bins: [ -2.5, -2.1, -1.7, -1, -0.5, 0, 0.5, 1, 1.7, 2.1, 2.5 ]
    xlabel: "L1Tau $\\eta$ (GeV)"
  L1Tau_Jet_pt:
    tau_var: true
    datasets: [ HTT, HH ]
    bins: [ 20, 25, 30, 35, 40, 50, 60, 70, 80, 90, 100, 120, 140, 160, 180, 200, 300, 500, 1000 ]
    major_ticks: [ 20, 30, 40, 50, 70, 100, 140, 200, 300, 500, 1000 ]
    minor_ticks: [ 60, 80, 90 ]
    xlabel: "PF Jet $p_{T}$ (GeV)"
    xscale: log
  GenHH_mass:
    tau_var: false
    datasets: [ HH ]
    bins: [ 250, 300, 350, 400, 450, 500, 550, 600, 700, 800, 900, 1000 ]
    xlabel: "gen $m_{HH}$ (GeV)"
  GenHtt_pt:
    tau_var: false
    datasets: [ HTT, HH ]
    bins: [ 0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 700, 800, 900, 1000 ]
    xlabel: "gen $H\\to\\tau\\tau$ $p_T$ (GeV)"
plots:
  diff_eff:
    variables: all
    datasets: all
    variants:
      ditau_v1:
        - algo: default_2tau
          color: k
        - algo: default_2tau_HT
          color: m
        - algo: nn_2tau_HTT_L1pt
          color: g
        - algo: nn_2tau_HTT_L1pt_HT
          color: b
        - algo: nn_2tau_HH_L1pt
          color: r
        - algo: nn_2tau_HH_L1pt_HT
          color: y
      ditau_v2:
        - algo: default_2tau
          color: k
        - algo: nn_2tau_HTT_L1pt
          color: g
        - algo: nn_2tau_HH_L1pt
          color: y
        - algo: nn_2tau_L1pt_eff
          color: b

lut_bins:
  nn_2tau_v2: [ 30, 32, 34, 36, 38, 40, 45, 50, 60, 70, 80, 90, 100, 120, 150, 200, 255 ]
  nn_2tau: [ 20, 23, 27, 30, 35, 40, 45, 50, 60, 70, 80, 100, 120 ]
  nn_1tau: [ 70, 80, 90, 100, 110, 120, 130, 140, 150 ]
algorithms:
  default_2tau:
    algo: default
    n_taus: 2
    pt_iso_thr: 34
    pt_noiso_thr: 70
  default_1tau:
    algo: default
    n_taus: 1
    pt_noiso_thr: 120
  L1_HT:
    algo: l1_flag
    l1_flag: L1_HTT280er
    valid_per_tau: false
  nn_2tau_L1pt_eff:
    algo: nn
    n_taus: 2
    lut_var: L1Tau_pt
    lut_bins: nn_2tau_v2
    thresholds_opt:
      dataset_eff: HTT
      dataset_rate: ZeroBias_2022G
      target_rate: default_2tau
      tau_eff_dataset: HH
      tau_eff_var: L1Tau_pt
      tau_eff_algo: default_2tau
      tau_eff_scale: 0.99
      step: 0.01
  nn_2tau_HTT_L1pt:
    algo: nn
    n_taus: 2
    lut_var: L1Tau_pt
    lut_bins: nn_2tau
    thresholds_opt:
      dataset_eff: HTT
      dataset_rate: ZeroBias_2022G
      extra_algos_eff: [ L1_HT ]
      target_rate: default_2tau
  nn_2tau_HH_L1pt:
    algo: nn
    n_taus: 2
    lut_var: L1Tau_pt
    lut_bins: nn_2tau
    thresholds_opt:
      dataset_eff: HH
      dataset_rate: ZeroBias_2022G
      extra_algos_eff: [ L1_HT ]
      target_rate: default_2tau
      initial_thresholds: nn_2tau_HTT_L1pt
  nn_2tau_HTT_ptReg:
    algo: nn
    n_taus: 2
    lut_var: L1Tau_ptReg
    lut_bins: nn_2tau
    thresholds_opt:
      dataset_eff: HTT
      dataset_rate: ZeroBias_2022G
      extra_algos_eff: [ L1_HT ]
      target_rate: default_2tau
      initial_thresholds: nn_2tau_HTT_L1pt
  nn_2tau_HH_ptReg:
    algo: nn
    n_taus: 2
    lut_var: L1Tau_ptReg
    lut_bins: nn_2tau
    thresholds_opt:
      dataset_eff: HTT
      dataset_rate: ZeroBias_2022G
      extra_algos_eff: [ L1_HT ]
      target_rate: default_2tau
      initial_thresholds: nn_2tau_HTT_ptReg
  nn_1tau_HTT_L1pt:
    algo: nn
    n_taus: 1
    lut_var: L1Tau_pt
    lut_bins: nn_1tau
    thresholds_opt:
      dataset_eff: HTT
      dataset_rate: ZeroBias_2022G
      extra_algos_eff: [ L1_HT, nn_2tau_HTT_L1pt ]
      target_rate: default_1tau
  nn_1tau_HH_L1pt:
    algo: nn
    n_taus: 1
    lut_var: L1Tau_pt
    lut_bins: nn_1tau
    thresholds_opt:
      dataset_eff: HH
      dataset_rate: ZeroBias_2022G
      extra_algos_eff: [ L1_HT, nn_2tau_HH_L1pt ]
      target_rate: default_1tau
      initial_thresholds: nn_1tau_HTT_L1pt
  nn_1tau_HTT_ptReg:
    algo: nn
    n_taus: 1
    lut_var: L1Tau_ptReg
    lut_bins: nn_1tau
    thresholds_opt:
      dataset_eff: HTT
      dataset_rate: ZeroBias_2022G
      extra_algos_eff: [ L1_HT, nn_2tau_HTT_ptReg ]
      target_rate: default_1tau
      initial_thresholds: nn_1tau_HTT_L1pt
  nn_1tau_HH_ptReg:
    algo: nn
    n_taus: 1
    lut_var: L1Tau_ptReg
    lut_bins: nn_1tau
    thresholds_opt:
      dataset_eff: HH
      dataset_rate: ZeroBias_2022G
      extra_algos_eff: [ L1_HT, nn_2tau_HH_ptReg ]
      target_rate: default_1tau
      initial_thresholds: nn_1tau_HTT_ptReg
  default_2tau_HT:
    algo: composite
    sub_algos:
      - default_2tau
      - L1_HT
  default_12tau_HT:
    algo: composite
    sub_algos:
      - default_1tau
      - default_2tau
      - L1_HT
  nn_2tau_HTT_L1pt_HT:
    algo: composite
    sub_algos:
      - nn_2tau_HTT_L1pt
      - L1_HT
  nn_2tau_HH_L1pt_HT:
    algo: composite
    sub_algos:
      - nn_2tau_HH_L1pt
      - L1_HT
  nn_2tau_HTT_ptReg_HT:
    algo: composite
    sub_algos:
      - nn_2tau_HTT_ptReg
      - L1_HT
  nn_2tau_HH_ptReg_HT:
    algo: composite
    sub_algos:
      - nn_2tau_HH_ptReg
      - L1_HT
  nn_12tau_HTT_L1pt_HT:
    algo: composite
    sub_algos:
      - nn_1tau_HTT_L1pt
      - nn_2tau_HTT_L1pt
      - L1_HT
  nn_12tau_HH_L1pt_HT:
    algo: composite
    sub_algos:
      - nn_1tau_HH_L1pt
      - nn_2tau_HH_L1pt
      - L1_HT
  nn_12tau_HTT_ptReg_HT:
    algo: composite
    sub_algos:
      - nn_1tau_HTT_ptReg
      - nn_2tau_HTT_ptReg
      - L1_HT
  nn_12tau_HH_ptReg_HT:
    algo: composite
    sub_algos:
      - nn_1tau_HH_ptReg
      - nn_2tau_HH_ptReg
      - L1_HT
resolution:
  ds_name: HH
  output_dir: perf/resolution
  columns:
    dataset:
      - L1Tau_pt
      - L1Tau_gen_pt
      - L1Tau_type
      - L1Tau_Jet_PNet_ptcorr
      - L1Tau_Jet_pt
    scores:
      - L1Tau_ptReg
  estimators:
    L1_pt:
      name: L1 $p_{T}$
      values: events['L1Tau_pt']
      color: red
    L3_PNet:
      name: L3 PNet-corrected $p_{T}$
      values: events['L1Tau_Jet_PNet_ptcorr'] * events['L1Tau_Jet_pt']
      validity: events['L1Tau_Jet_pt'] > 20
      color: green
    L1_ptReg:
      name: L1 NN $p_{T}$
      values: scores['L1Tau_ptReg']
      color: blue
  bin_settings:
    combined:
      bins: [ 20, 22, 24, 26, 28, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120, 150, 200, 250 ]
      x_label: "gen visible $p_{T}$ (GeV)"
      y_label: "$p_T^{reco} / p_T^{gen} - 1$"
      title: "$p_T$ reconstruction performance"
      alpha_fill: 0.2
    diff:
      n_bins: 50
      range_factor: 2
      x_label: "$p_T^{reco} - p_T^{gen}$"
      y_label: a.u.
      title: "{:.0f} < $p_T^{{gen}}$ < {:.0f} GeV"
      bin_name: "bin_{:.0f}_{:.0f}"
    diff_rel:
      n_bins: 50
      range: 1
      x_label: "$p_T^{reco} / p_T^{gen} - 1$"
      y_label: a.u.
      title: "{:.0f} < $p_T^{{gen}}$ < {:.0f} GeV"
      bin_name: "bin_{:.0f}_{:.0f}_rel"
