setup:
  qbits: 8
  # l1reg: 0.000001
  init: he_uniform
  learning_rate: 0.0001
  weight_decay: 0.1
  regress_pt: false
  reduce_calo_precision: 0
  reduce_center_precision: 0
  apply_avg_pool: true
  concat_input: true

layers:
  - type: dense
    units: 42
    prune: 0
    prune_begin: 2000
    prune_freq: 2000
  - type: dense
    units: 16
    prune: 0
    prune_begin: 2000
    prune_freq: 2000
  - type: dense
    units: 1
    is_output: true
