setup:
  qbits: 8
  l1reg: 0.00001
  init: lecun_uniform
  learning_rate: 0.0001
  weight_decay: 0.01
  regress_pt: false

layers:
  - type: conv
    kernel_size: [ 2, 3 ]
    strides: [ 2, 3 ]
    filters: 6
  - type: conv
    kernel_size: [ 3, 3 ]
    strides: [ 3, 3 ]
    filters: 12
  - type: dense
    units: 16
  - type: dense
    units: 8
  - type: concat
  - type: dense
    units: 32
    # prune: 0.5
    # prune_begin: 1000
    # prune_freq: 1000
  - type: dense
    units: 16
    # prune: 0.5
    # prune_begin: 1000
    # prune_freq: 1000
  - type: dense
    units: 1
    is_output: true
